const domain_URL = process.env['domain_URL'];
const APP_VERSION = process.env['APP_VERSION'];
const JWT_SIGNATURE = process.env['JWT_SIGNATURE'];
const VERSION_NAME = process.env['VERSION_NAME'];
const SKIP_DEVELOPER_MODE_CHECK = process.env['SKIP_DEVELOPER_MODE_CHECK'];
export {domain_URL};
export {APP_VERSION};
export {JWT_SIGNATURE};
export {VERSION_NAME};
export {SKIP_DEVELOPER_MODE_CHECK};
